oro_issue:
    resource: "@OroIssueBundle/Resources/config/routing.yml"

oro_project:
    resource: "@OroProjectBundle/Resources/config/routing.yml"

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"
