parameters:
    oro.sender_email: tracker@example.com
    oro.sender_name: Tracker Service Team

services:
    issue.listener:
        class: Oro\IssueBundle\EventListener\IssueListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }

    comment.listener:
        class: Oro\IssueBundle\EventListener\CommentListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    activity.listener:
        class: Oro\IssueBundle\EventListener\ActivityListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oro.security.comment_voter:
        class: Oro\IssueBundle\Security\CommentVoter
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: security.voter }

    oro.security.issue_voter:
        class: Oro\IssueBundle\Security\IssueVoter
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: security.voter }
