Oro\IssueBundle\Entity\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            { fields: code, message: 'issue.validators.code_in_use' }
        - Callback:
            methods: [validateParentIssue]

    properties:
        code:
            - NotBlank: ~
        summary:
            - NotBlank: ~
        createdAt:
            - DateTime: ~
        updatedAt:
            - DateTime: ~
        project:
            - NotBlank: ~
Oro\IssueBundle\Entity\IssueComment:
    properties:
        content:
            - NotBlank: ~
        createdAt:
            - DateTime: ~
