services:

    oro.security.user_voter:
        class: Oro\UserBundle\Security\UserVoter
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: security.voter }
