Oro\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            { fields: email, message: "user.validators.email_in_use" }
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            { fields: username, message: "user.validators.username_in_use" }
    properties:
        email:
            - NotBlank: { message: "user.validators.email_not_blank" }
        password:
            - NotBlank: ~
        username:
            - NotBlank: ~
        avatar_file:
            - File:
                maxSize: 6000000
